apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statex-ecosystem
  namespace: statex-apps
  labels:
    app: statex-ecosystem
    managed-by: k8s-migration
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - statex-ecosystem.alfares.cz
      secretName: statex-ecosystem-tls
  rules:
    - host: statex-ecosystem.alfares.cz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: statex-ecosystem
                port:
                  number: 4710
