apiVersion: v1
kind: Service
metadata:
  name: statex-ecosystem
  namespace: statex-apps
  labels:
    app: statex-ecosystem
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: statex-ecosystem
  ports:
    - protocol: TCP
      port: 4710
      targetPort: 4710
      name: app
